name: Periodic Health Check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Server Health
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://full-stack-open-pokedex-ij40.onrender.com'