name: Deployment pipeline
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: trigger render deploy using render hook, only on push to main
        if: ${{ github.event_name == 'push'  && github.ref == 'refs/heads/main' && !contains(toJson(github.event.commits.*.message), '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  bump_version_and_push_tag:
    runs-on: ubuntu-latest
    needs: simple_deployment_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push'  && github.ref == 'refs/heads/main' && !contains(toJson(github.event.commits.*.message), '#skip')}}
        uses: anothrNick/github-tag-action@1.73.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TAG_PREFIX: 'v'
            DEFAULT_BUMP: patch
  discord_notification:
    runs-on: ubuntu-latest
    needs: simple_deployment_pipeline
    steps:
      - name: Test success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          text: The deployment succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          text: The deployment failed! https://github.com/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.event.head_commit.author.username }} broke the build.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test cancelled
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: cancelled()
        with:
          severity: warning
          text: The deployment was cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


